apiVersion: v1
kind: Pod
metadata:
  name: containerproxy
  labels:
    ci: containerproxy-build
spec:
  securityContext:
    fsGroup: 65534
  containers:
    - name: containerproxy-build
      image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/containerproxy-build
      securityContext:
        privileged: true
      command: [ "sh" ]
      args: [ "/usr/src/app/docker-entrypoint.sh" ]
      tty: true
      volumeMounts:
        - name: workspace-volume
          subPath: docker
          mountPath: /var/lib/docker
      resources:
        requests:
          ephemeral-storage: "20Gi"
          memory: "2Gi"
          cpu: "1.0"
        limits:
          memory: "4Gi"
          cpu: "1.5"
          ephemeral-storage: "20Gi"
